- name: import nodejs setup 
  ansible.builtin.import_role:
    name: common 
    tasks_from: appsetup.yaml

- name: import app setup role 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml