- name: "copy {{ component }} service"
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: daemon reload enable and start
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    enabled: true
    state: started